GalleryApp/Models/AddViewModel.cs
using Amazon.Util.Internal;
using GalleryApp.Model;
using System.ComponentModel.DataAnnotations;

namespace GalleryApp.Models
{
    public class AddViewModel
    {
        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        public int CategoryId { get; set; }

        public List<CategoryViewModel> Categories { get; set; }

    }
}

GalleryApp/Models/AllViewModel.cs
using System.Reflection.Metadata.Ecma335;

namespace GalleryApp.Models
{
    public class AllViewModel
    {
        public Guid Id { get; set; }
        public string Title { get; set; }

        public string? Category { get; set; }
        public ImageViewModel GalleryImage { get; set; }
    }
}

GalleryApp/Models/DetailsViewModel.cs
namespace GalleryApp.Models
{
    public class DetailsViewModel
    {
        public Guid Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public List<ImageViewModel> Images { get; set; }
    }
}

GalleryApp/Models/EditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GalleryApp.Models
{
    public class EditViewModel
    {
        public Guid Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        public int CategoryId { get; set; }
        public  List<CategoryViewModel> Categories { get; set; }
    }
}

GalleryApp/Controllers/GalleryController.cs
using GalleryApp.Data;
using GalleryApp.Model;
using GalleryApp.Model.MongoDbModel;
using GalleryApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MongoDB.Driver;
using static GalleryApp.Extensions.ClaimsExt; 

namespace GalleryApp.Controllers
{
    public class GalleryController : Controller
    {
        private GalleryAppDbContext _dbContext;
        private IMongoCollection<GalleryImagesFiles> _mongoCollection;
       
        public GalleryController(GalleryAppDbContext dbContext,IMongoDatabase mongoDatabase)
        {
            _dbContext = dbContext;
            _mongoCollection = mongoDatabase.GetCollection<GalleryImagesFiles>("GalleryApp");
        }

        [HttpPost]
        public async Task<IActionResult> DelatePicture(string fileName,string Id) 
        {

            var galleryPicture = await _dbContext.GalleryImages.Where(x => x.FileName == fileName).FirstOrDefaultAsync();

            if (galleryPicture == null) 
            {
                return Content("fail");
            }

             _dbContext.GalleryImages.Remove(galleryPicture);

            await _dbContext.SaveChangesAsync();

            return Content("success");
        }

        public async Task<IActionResult> Details(Guid id) 
        {
            var getGallery = await _dbContext.Galleries.Where(x => x.Id == id)
                  .Select(y => new DetailsViewModel()
                  {
                      
                      Title=y.Title,
                      Description=y.Description,
                      Images=y.GalleryImages.Select(z=>new ImageViewModel() 
                      {
                          FileName=z.FileName,
                          Extensions = z.Ext
                          
                      }).ToList()

                  }).FirstOrDefaultAsync();
               

            return View(getGallery);
        }

        public async Task<IActionResult> Edit(string id) 
        {
            var categories = await _dbContext.Categories.Select(x=>new CategoryViewModel() 
            {
                Id = x.Id,
                Name = x.Name
            }).ToListAsync();

            var getGalleryForEdit = await _dbContext.Galleries.Where(x => x.Id.ToString() == id).Select(y => new EditViewModel()
            {
                Id = y.Id,
                Title = y.Title,
                Description = y.Description,
                Categories = categories
                
            }).FirstOrDefaultAsync();

            return View(getGalleryForEdit);
        }
     
        [HttpPost]
        public async Task<IActionResult> Edit(EditViewModel editViewModel)
        {
            Gallery gallery = await _dbContext.Galleries.Where(x => x.Id == editViewModel.Id).FirstOrDefaultAsync();

            if (gallery==null)
            {
                return NotFound();
            }

            gallery.Title = editViewModel.Title;
            gallery.Description = editViewModel.Description;
            gallery.CategoriesId = editViewModel.CategoryId;

            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> All()
        {
            var view = await _dbContext.Galleries.Select(x => new AllViewModel()
            {
                Id = x.Id,
                Title = x.Title,
                Category = x.Categories.Name,
                GalleryImage = x.GalleryImages.Select(y=>new ImageViewModel() 
                {
                   FileName = y.FileName,
                   Extensions = y.Ext
                }).FirstOrDefault()
             
            }).ToListAsync();

           

            return View(view);
        }

        [HttpGet]
        public async Task<IActionResult> Add() 
        {
            var ctagories = await _dbContext.Categories.Select(x => new CategoryViewModel()
            {
                Id = x.Id,
                Name = x.Name,                
            }).ToListAsync();

            AddViewModel view = new AddViewModel();
        
            view.Categories = ctagories;
          

            return View(view);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddViewModel view,IFormFile fileData) 
        {
            var getUserId = this.User.GetCurrentUser();
            // create object for Gallery without Image!!! (for SQL)
            Gallery gallery = new Gallery()
            {
                Title = view.Title,
                Description = view.Description,
                CategoriesId = view.CategoryId,
                AppUserId = getUserId
                  
            };


            await _dbContext.Galleries.AddAsync(gallery);
            await _dbContext.SaveChangesAsync();

            var fileName = $"{Guid.NewGuid()}{Path.GetExtension(fileData.FileName)}";
            var extension = Path.GetExtension(fileData.FileName).TrimStart('.');

            // create object for image (for SQL)
            GalleryImages galleryImages = new GalleryImages()
            {
                FileName = fileName,
                Ext = extension,
                GalleryId = gallery.Id
            };

            // open stream to add file data in MongoDB 
            using (MemoryStream stream = new MemoryStream()) 
            {
                await fileData.CopyToAsync(stream);

               // create object(object from type (model for MongoDb)) for mongodb
                GalleryImagesFiles galleryImagesFiles = new GalleryImagesFiles()
                {
                    FileData = stream.ToArray(),
                    FileName = fileName,
                    GalleryId = gallery.Id.ToString(),
                    Extension = extension
                };
             
                await _mongoCollection.InsertOneAsync(galleryImagesFiles);
            }

            await _dbContext.GalleryImages.AddAsync(galleryImages);
            await _dbContext.SaveChangesAsync();


           return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> GetImage(string fileName) 
        {
            var imageFile = await _mongoCollection.Find(x => x.FileName == fileName).FirstOrDefaultAsync();

            if (imageFile == null || imageFile.FileData == null)
            {
                return NotFound();
            }

            return File(imageFile.FileData,$"image/{imageFile.Extension}");
        }

        
    }
}

GalleryApp/Views/Gallery/Add.cshtml
@model AddViewModel

<style>



    .row {
        border: 2px solid black;
        margin-left: 20em;
        margin-right: 20em;
        align-items: center;
        padding-top: 5em;
        padding-bottom: 5em;
    }

    .form-group{
        
        padding-top:inherit.5em;
       
    }
    .form-container {
    }

</style>

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <div class="form-container">

            <div class="form-header">
                <h3>Create a Photo Gallery</h3>
            </div>
            <form asp-controller="Gallery" asp-action="Add" method="post" enctype="multipart/form-data" class="p-4">
                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" placeholder="Title...">
                    <span asp-validation-for="Title" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description"></label>
                    <input asp-for="Description" class="form-control"
                           placeholder="Duaration of the trip">
                    <span asp-validation-for="Description" class="small text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="@Model.CategoryId" class="form-label">Select type of photography</label>
                        <select asp-for="@Model.CategoryId" class="form-control">
                                @foreach (var category in Model.Categories)
                                {
                                    <option value="@category.Id">@category.Name</option>
                                }
                        </select>
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label for="file">Upload Image</label>
                    <input type="file" name="fileData" required class="form-control mb-3" />
                </div>


                <div class="text-center">
                    <input class="btn btn-primary mt-3 w-50" type="submit" value="Create Gallery" />
                </div>
            </form>

           

        </div>
    </div>
</div>

GalleryApp/Views/Gallery/All.cshtml
@model List<AllViewModel>

<style>
    .section-heder {
        text-align: center;
        border-bottom: 1px solid black;
        margin-top: 2em;
        margin-bottom: 5em;
        padding-bottom: 2em;
    }

    .cards-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: left;
        padding-left: 3em;
        /* Фон с градиент, наподобяващ стара фотография */
        background: linear-gradient(to bottom,#fcab08 0%, #e0e0e0 100%);
    }

    .card {
        border: 5px solid #d2b48c; /* Рамка, която наподобява стара фотография */
        border-radius: 1em;
        flex: 0 0 22%;
        box-shadow: 0 0 45px rgba(0, 0, 0, .2);
        margin-left: 2em;
        overflow: hidden;
        background-color: #fafafa; /* Фон на картичката */
    }

    .card img {
        width: 100%;
        height: 250px;
        object-fit: cover;
        filter: sepia(0.8) contrast(0.9); /* Ефект на старина и контраст */
        transition: .5s;
    }

    .card:hover img {
        transform: scale(1.05);
    }

    .card-body h6, .card-body p {
        font-family: 'Permanent Marker', cursive; /* Шрифт, който наподобява ръчно писане с маркер */
        color: #333;
    }

    .btn {
        border-radius: 0.5em;
    }
</style>

<div class="section-heder">
    <h2>All Galleries</h2>
    <article class="some-h">
        <p>
            See our gallery or go and create gallery
        </p>
        <a asp-controller="Gallery" asp-action="Add" class="btn btn-primary">Create</a>
    </article>
</div>

<div class="cards-container">
    @foreach (var gallery in Model)
    {
        <div class="card mb-3">
            @if ((gallery.GalleryImage != null))
            {
                <img class="card-img-top" src="@Url.Action("GetImage", "Gallery", new { fileName = gallery.GalleryImage.FileName })" alt="Gallery Image not found">
            }
            <div class="card-body text-center">
                <h6>@gallery.Title</h6>

                @if (gallery.Category == null)
                {
                    <p>Category: No category selected</p>
                }
                else {
                    <p>Category: @gallery.Category</p>
                }

                <a asp-controller="Gallery" asp-action="Details" asp-route-id="@gallery.Id" class="btn btn-success">Details</a>
                <a asp-controller="Gallery" asp-action="Edit" asp-route-id="@gallery.Id" class="btn btn-success">Edit</a>
            </div>
        </div>
    }
</div>

GalleryApp/Views/Gallery/Delete.cshtml
@{
}

GalleryApp/Views/Gallery/Details.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Gallery</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            background-color: #f4f4f4;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        .gallery {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-wrap: wrap;
            flex-direction: row;
            background-color: #fff;
            margin: 20px auto;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        .gallery-item {
            flex: 0 0 80%;
            text-align: center;
            justify-content: stretch;
            display: none;
            border-radius: 3em;
        }

            .gallery-item img {
                width: 80%;
                height: auto;
                transition: transform 0.5s;
                border-radius:0.2em;
                box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            }

        .gallery-controls {
            display: flex;
            justify-content: space-between;
            margin-top: 5px;
        }

            .gallery-controls button {
                background-color: #66B2FF;
                color: white;
                border: none;
                padding: 10px 20px;
                margin: 0 10px;
                cursor: pointer;
                border-radius: 5px;
                transition: background-color 0.3s;
            }

                .gallery-controls button:hover {
                    background-color: #3399FF;
                }

        .info-content-section {
            display: flex;
            justify-content: space-around;
            align-items: center;
            margin-bottom: 5em;
            background-color: #99CCFF;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        .info-section, .author-section {
            text-align: center;
        }

            .author-section a {
                background-color: #66B2FF;
                color: white;
                padding: 5px 15px;
                text-decoration: none;
                border-radius: 5px;
                transition: background-color 0.3s;
            }

                .author-section a:hover {
                    background-color: #3399FF;
                }

    </style>
</head>
<body>
    <h1>Image Gallery</h1>

    <!-- Gallery Container -->
    <div class="gallery">
       @* @foreach (var image in Model.Images)
        {
            <div class="gallery-item">
                <img src="@Url.Action("GetImage", "Gallery", new { fileName = image.FileName })" alt="Gallery Image">
            </div>

           

        }*@
        @if (Model.Images.Count>0)
        {
            @for (var i = 0; i < Model.Images.Count; i++)
            {
                <div class="gallery-item">
                    <img src="@Url.Action("GetImage", "Gallery", new { fileName = Model.Images[i].FileName })" alt="Gallery Image">
                </div>

                <button onclick="deleteImage('@Model.Images[i].FileName', '@Model.Id')" class="btn btn-danger delete-button">Delete</button>
            }

        }
        else{

            <h1>There is no picture for now</h1>
        }
        
        
        
        
        
      

        <div class="camera-style">
            <p>Description: @Model.Description</p>

            <!-- Gallery Controls -->
            <div class="gallery-controls">
                <button onclick="plusSlides(-1)">&#10094; Previous</button>
                <button onclick="plusSlides(1)">&#10095; Next</button>
            </div>
        </div>

     
       
      
    </div>


    <!-- Info Content Section -->
    <div class="info-content-section">
        <section class="info-section">
            <p>Title: @Model.Title</p>
            <p>Description: @Model.Description</p>
            <p>Count of pictures: @Model.Images.Count</p>
        </section>
        <section class="author-section">
            <p>ChEck my galleries</p>
            <a asp-action="All" asp-controller="Gallery">More Galleries</a>
        </section>
    </div>

    <!-- JavaScript for Gallery -->
    <script>
        let slideIndex = 1;
        showSlides(slideIndex);

        function plusSlides(n) {
            showSlides(slideIndex += n);
        }

        function showSlides(n) {
            const galleryItems = document.querySelectorAll('.gallery-item');
            if (n > galleryItems.length) slideIndex = 1;
            if (n < 1) slideIndex = galleryItems.length;
            galleryItems.forEach(item => item.style.display = 'none');
            galleryItems[slideIndex - 1].style.display = 'block';
        }
    </script>

    <script>
        function deleteImage(fileName, Id) {
            if (confirm('Are you sure you want to delete this image?')) {
                fetch(`/Gallery/DelatePicture?fileName=${fileName}&tourId=${Id}`, {
                    method: 'POST'
                })
                    .then(response => response.text())
                    .then(data => {
                        if (data === 'success') {
                            alert('Image deleted successfully');
                            location.reload();
                        } else {
                            alert('Failed to delete image');
                        }
                    });
            }
        }

    </script>
</body>
</html>

GalleryApp/Views/Gallery/Edit.cshtml
@{
}

@model EditViewModel

<style>

    .form-header{
        text-align:center;
        border:2px solid red;
    
    }

    .row {
        border: 2px solid black;
        margin-left: 20em;
        margin-right: 20em;
        align-items: center;
        padding-top: 5em;
        padding-bottom: 5em;
    }

    .form-container {

       padding-top:2em;
    }

    .btn{
        
        border-radius:1em;
        transition: background-color 0.5s,transform 0.5s;      
        
    }

    .btn:hover{
            background-color: #0056b3; 
            transform:translateY(-1px);
    
    }



</style>

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <div class="form-container">

            <div class="form-header">
                <h3>Edit Gaery</h3>
            </div>
            <form asp-controller="Gallery" asp-action="Edit" asp-route-Id="@Model.Id" method="post" enctype="multipart/form-data" class="p-4">
                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" placeholder="Title...">
                    <span asp-validation-for="Title" class="small text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description"></label>
                    <input asp-for="Description" class="form-control"
                           placeholder="Duaration of the trip">
                    <span asp-validation-for="Description" class="small text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="@Model.CategoryId" class="form-label">Select type of photography</label>
                    <select asp-for="@Model.CategoryId" class="form-control">
                        @foreach (var category in Model.Categories)
                        {
                            <option value="@category.Id">@category.Name</option>
                        }
                    </select>
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>


                <div class="text-center">
                    <input class="btn btn-primary mt-3 w-50" type="submit" value="Edit" />
                </div>
            </form>



        </div>
    </div>
</div>